#
# A Dockerfile for generating an image quick&fast from a local build
#

FROM opensuse/leap:15.0

ARG BUILD_DIR="/go/src/github.com/kubic-project/registries-operator"
ARG BUILT_EXE="cmd/registries-operator/registries-operator"

COPY $BUILT_EXE /usr/local/bin/registries-operator
RUN  chmod 755 /usr/local/bin/registries-operator

CMD ["/usr/local/bin/registries-operator"]
